In [18]:
import sqlite3
import pandas as pd 

con=sqlite3.connect(r'../data/raw/ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [19]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script = f.read()  
    con.executescript(script)
    con.commit()
    print('ran', path)

In [20]:
import ast
import pandas as pd
d = pd.read_sql('select * from deliveries where fielders_involved is not null', con)
d['fielders'] = d['fielders_involved'].apply(ast.literal_eval)

d = d.explode('fielders')

d['fielders'].value_counts().head(5)

fielders
MS Dhoni          258
KD Karthik        228
RV Uthappa        169
AB de Villiers    148
V Kohli           142
Name: count, dtype: int64

In [21]:
q("""select result, count(*)as n
FROM matches
GROUP BY result""")

      result     n
0  no result     9
1        tie    16
2        win  1187

In [22]:
q("""
 -- what is the strike rate of every batter in the death overs 
 
 select 
        batter,
        ROUND(
        100*SUM(batter_runs) / SUM(
            CASE 
                WHEN is_wide_ball=0 AND is_no_ball=0
                THEN 1
                ELSE 0
            end 
        ), 2
    ) AS strike_rate

from deliveries
where over_number BETWEEN 15 AND 19
   and is_super_over=0
GROUP BY batter
ORDER BY strike_rate DESC;
""")

             batter  strike_rate
0          WG Jacks        483.0
1          DT Patil        400.0
2        KT Maphaka        400.0
3            L Wood        300.0
4          PA Reddy        300.0
..              ...          ...
637     Sunny Gupta          0.0
638          U Kaul          0.0
639  V Pratap Singh          0.0
640   Y Prithvi Raj          0.0
641      YA Abdulla          0.0

[642 rows x 2 columns]

In [23]:
run_sql_file(r'C:\Users\Scalefusion admin\OneDrive\Documents\OJT- SEM 3\project_3.1 sem 3\sql\09_analysis_views.sql')

ran C:\Users\Scalefusion admin\OneDrive\Documents\OJT- SEM 3\project_3.1 sem 3\sql\09_analysis_views.sql

In [24]:
q("""select * FROM v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [25]:
q("""select phase, count(*) from v_ball GROUP BY phase;""")

       phase  count(*)
0      Death     65488
1     Middle    132173
2  Powerplay     90390

In [26]:
run_sql_file(r'C:\Users\Scalefusion admin\OneDrive\Documents\OJT- SEM 3\project_3.1 sem 3\sql\09_analysis_views.sql')

ran C:\Users\Scalefusion admin\OneDrive\Documents\OJT- SEM 3\project_3.1 sem 3\sql\09_analysis_views.sql

In [ ]:
q("""select * from v_innings ;""")

,match_id,innings,batting_team,bowling_team,runs,wickets,legal_balls
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,222,3,120
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10,91
2,335983,1,Chennai Super Kings,Punjab Kings,240,5,120
3,335983,2,Punjab Kings,Chennai Super Kings,207,4,120
4,335984,1,Rajasthan Royals,Delhi Capitals,129,8,120
...,...,...,...,...,...,...,...
2413,1529284,2,Sunrisers Hyderabad,Mumbai Indians,249,4,112
2414,1529285,1,Royal Challengers Bangalore,Gujarat Titans,155,10,116
2415,1529285,2,Gujarat Titans,Royal Challengers Bangalore,158,6,95
2416,1529286,1,Rajasthan Royals,Delhi Capitals,225,6,120
2417,1529286,2,Delhi Capitals,Rajasthan Royals,226,3,115

In [28]:
q("""select * from v_match_totals;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_decision,first_innings_runs,bat_first_team,chase_won
0,335982,M chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,field,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,field,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,field,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,field,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,field,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,field,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,field,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,bat,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,field,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,bat,225,Rajasthan Royals,1

In [29]:
q("""select count(*) from v_match_totals;""")

   count(*)
0      1187

In [30]:
q("""select count(*) from v_innings;""")

   count(*)
0      2418

In [31]:
q("""select phase,count(*) from v_ball;""")

       phase  count(*)
0  Powerplay    288051